name: "Build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300

    - name: Restore
      run: dotnet restore
      
    - name: Setup .NET Core SDK Again
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300

    - name: Restore Again
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore -bl:${{ matrix.os }}.binlog

